apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base-application
  namespace: flux-system
spec:
  interval: 5m
  path: ./manifests/base-application
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system